baseURL = 'https://example.org/'
languageCode = 'fr-FR'
title = 'HugoLearn'
theme = 'ananke'

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
enableRobotsTXT = true

[languages]
  [languages.fr]
    weight = 1
    contentDir = "content/fr"
  [languages.en]
    weight = 2
    contentDir = "content/en"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/maxence-breuilles/"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/MisterAzix"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/MaxenceBr_"

[related]
includeNewer = true

[[related.indices]]
name = 'courses'
type = 'fragments'
weight = 1
